### PR TITLE
Changes media url in README

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Changes media url from tools.taskcluster.net to media.tastcluster.net

Related to [Bugzilla#1534367](https://bugzilla.mozilla.org/show_bug.cgi?id=1534367)

### CODE REVIEW

**Review by djmitche — CHANGES_REQUESTED** [review]
Hm, this one didn't come out right -- I think because this is a .rst file?  It might be easiest to just rewrite it to a markdown file.

**Comment by arshadkazmi42** [comment]
Should I create a new `README.md` file or just change existing `README.rst` to `README.md` ?

**Comment by djmitche** [comment]
I think rename and edit the file so that it's valid markdown.

**Review by djmitche — APPROVED** [review]
:balloon:

**Pull request merged**
