### PR TITLE
Update publishing steps to also generate a universal wheel

### LINKED ISSUE #6: Provide wheel distribution on PyPI
Hi!

Please could this package also by made available as a wheel on PyPI?
https://pypi.python.org/pypi/slugid/1.0.7

Wheels have the following advantages:
* Faster installation time
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.
* ...and more - see: http://pythonwheels.com

This package is pure Python and supports both Python 2 and 3, so can be distributed as a "universal wheel":
https://packaging.python.org/tutorials/distributing-packages/#wheels

To save having to pass `--universal` to `setup.py` each time, the pref can be saved in `setup.cfg`:

```
[bdist_wheel]
universal=1
```

The Python packaging guide recommends using [Twine](https://github.com/pypa/twine) to upload packages:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

So with the `setup.cfg` as above, the steps for building/uploading a new release are then:

```bash
$ pip install -U twine setuptools wheel
$ rm -rf dist/ build/
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

The PyPI package listing will then display two entries for the new release, one with type "Source" and the other "Python Wheel".

Many thanks :-)

### PR DESCRIPTION
**Pull request by edmorley**
Fixes #6.

### CODE REVIEW

**Comment by edmorley** [comment]
@petemoore, no rush but could you review at some point? :-)

**Comment by petemoore** [comment]
> @petemoore, no rush but could you review at some point? :-)

Hey @edmorley sorry about that, I was on PTO for the last two weeks! Looking at it now.

**Review by petemoore — APPROVED** [review]
Hey @edmorley ,

Based on the details you provided in #6 should we also add `setuptools` and `wheel` to `requirements.txt`?

Thanks for the PR! :-)

Pete

**Comment by edmorley** [comment]
> Based on the details you provided in #6 should we also add setuptools and wheel to requirements.txt?

From IRC for posterity:

_emorley:_ I think that typically adding setuptools/wheel to the app's requirements.txt is considered not best practice, since they are needed before installing the requirements (eg during python/pip bootstrap)
_emorley:_ the pip install script installs both
_pmoore:_ ah cool
_pmoore:_ then i'll land it!

**Pull request merged**
